services:
  - type: web
    name: 88campcar
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASS_HASH
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: BASE_URL
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/storage
    disk:
      name: uploads
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
